filegroup(
    name = "templates",
    srcs = [
        "istio-egress.yaml",
        "istio-ingress.yaml",
        "istio-manager.yaml",
        "istio-mixer.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "redis_backend",
    srcs = [
        "redis.yaml",
    ],
    visibility = ["//visibility:public"],
)
